### ISSUE TITLE
Amazing

### ISSUE THREAD

**Issue by alexmingoia** [FelixMcFelix/Shallot#1]
This is amazing (the code and your dissertation). 👍 

A few weeks ago I had my own revelation, "why can't I visit a website that acts as an onion-router, using browsers as nodes via WebRTC?" Today I decided to implement it, and after a quick search I found this project. You beat me to the punch!

**Comment by alexmingoia** [comment]
Do you hang on IRC at all, or other networks? I have a few applications I'd like to build on top of webrtc onion routing and DHT

**Comment by FelixMcFelix** [comment]
@alexmingoia Wow, I'm glad you think so highly of this! I'm primarily on Discord nowadays (as FelixMcFelix#2443), although I'm not averse to IRC or anything like that.

I'm flattered that you've taken a shining to the project, but there are key issues with the underlying stack -- particularly concerning stability for the server node (which relies on a slightly buggy webrtc plugin) as well as the numerous security issues detailed in the report. Although an interesting toy/testing ground, it does need further work to be secure and reliable. If you have any questions though, feel free to ask!
